import { Geist, Geist_Mono } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
import { ThemeProvider } from "next-themes";
import CustomCursor from "@/components/CustomCursorWrapper";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import ContactCTA from "@/components/ContactCTA";
import ActionCursor from "@/components/ActionCursor";
import { GoArrowUpRight } from "react-icons/go";
import AuthSessionProvider from "@/components/auth/session-provider";
import { Suspense } from "react";
import { Toaster } from "@/components/ui/sonner";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const Oldschool = localFont({
  src: [
    {
      path: "../public/fonts/Oldschool Grotesk Light.otf",
      weight: "400",
      style: "base",
    },
    {
      path: "../public/fonts/Oldschool Grotesk Bold.otf",
      weight: "700",
      style: "bold",
    },
    {
      path: "../public/fonts/Oldschool Grotesk Medium.otf",
      weight: "600",
      style: "Medium",
    },
    {
      path: "../public/fonts/Oldschool Grotesk Regular.otf",
      weight: "500",
      style: "normal",
    },
  ],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${Oldschool.className} antialiased`}
      >
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <Header />
          <Suspense fallback={<div>Loading...</div>}>
            <AuthSessionProvider>{children}</AuthSessionProvider>
          </Suspense>
          <CustomCursor />
          <ActionCursor defaultIcon={<GoArrowUpRight className="w-10 h-10 text-black" />} />
          <ContactCTA />
          <Toaster />
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  );
}
